title: "Snow Peak Festival Products"
baseurl: "/snowpeak-sepposai"
url: "https://encyphered.github.io"
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
kramdown:
  toc_levels: 1..2
plugins:
  - jekyll-include-cache